### ISSUE TITLE
hexefx_t41gfx i2s2 not working

### ISSUE THREAD

**Issue by darwin1234** [hexeguitar/TGX4#1]
Hello,

I am trying to use I2S2 with the WM8731 audio codec from Open Music Labs, but it doesn't seem to be working.

![image](https://github.com/hexeguitar/TGX4/assets/8327269/2ffd7100-1b7c-4a72-b989-6319b07e4651)

![441514357_1498950053991348_751243207599412376_n](https://github.com/hexeguitar/TGX4/assets/8327269/a29f4794-7292-4bcb-b2f2-4c6dd3122278)

Could you kindly share the details of your connection setup? Additionally, if you have any tips or common troubleshooting steps for this setup, I would greatly appreciate it.

Thank you!

**Comment by hexeguitar** [comment]
Here is the Teensy pinout used with WM8731 and I2S2
```
I2S_MCLK:   33 (MCLK2)
I2S_BCK:     4 (BCLK2)
I2S_LRCLK:   3 (LRCLK2)
I2S_DACIN:   2 (OUT2) - WM8731 data in
I2S_ADC_OUT: 5 (IN2) - WM8731 data out

I2C_SDA:     18 (pull up 2k2)
I2C_SCL:     19: (pull up 2k2)
```

Troubleshooting:
1. Make sure the MCLK is present, it should be about 11.289MHz (44.1kHz * 256). Without it the WM8731 will not respond via i2c.
2. Check if the I2C can access the codec and configure it. The terminal window should output "Codec init fail" after reset in that case. You can also switch to the console window and run **i2c** command, it will scan all the devices on the I2C bus.**0x1A** is the codec's address.
3. Check the I2S bit clock, around 2.8MHz
4. Check the LRCLK, should be equal to the sampling rate: 44.1kHz
5. Check the data lines for activity

Oh - and in case you use the onboard jacks - the output is the headphone out. hexefx_t41gfx config uses Line outputs, headphone out is muted. However, there is no DC blocking present on the Audio Codec Shield and it has to be added externally. Otherwise there will be about 1.6V DC present on the line outputs.
![lout](https://github.com/hexeguitar/TGX4/assets/7537766/c98a0c68-5e84-436d-b9fe-0544c6cdf725)

Also - the interface is I2S, not SPI as in the description of the Codec Board. SPI can emulate I2S and it has been done on 8bit Arduinos. Teensy uses regular audio I2S interface. Judging from the pic, you have connected it to the SPI bus.

Hope it helps!
